export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const DISPLAY_ITEM_DETAILS = 'DISPLAY_ITEM_DETAILS'

export const DELETE_ITEM = 'DELETE_ITEM'

export const ADD_ITEM_TO_LIST = 'ADD_ITEM_TO_LIST'
export const DELETE_ITEM_TO_LIST = 'DELETE_ITEM_TO_LIST'

export const ADD_ITEM_TOOGLE_BUTTON = 'ADD_ITEM_TOOGLE_BUTTON'

export const BACK_BUTTEN = 'BACK_BUTTEN'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_ITEM_BEGIN = 'CREATE_ITEM_BEGIN'
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS'
export const CREATE_ITEM_ERROR = 'CREATE_ITEM_ERROR'

export const GET_ITEMS_BEGIN = 'GET_ITEMS_BEGIN'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'

export const SET_EDIT_ITEM = 'SET_EDIT_ITEM'

export const DELETE_ITEM_BEGIN = 'DELETE_ITEM_BEGIN'

export const EDIT_ITEM_BEGIN = 'EDIT_ITEM_BEGIN'
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS'
export const EDIT_ITEM_ERROR = 'EDIT_ITEM_ERROR'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const CHANGE_PAGE = 'CHANGE_PAGE'

export const SET_QUESTION = 'SET_QUESTION'
