import img from '../images/img.jpg'
const List = [
  {
    id: 1,
    image: img,
    name: 'tamoto',
    totalItems: 1,
    category: 'fruit and vegetable',
    note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi itaque vero culpa, corporis nihil quibusdam expedita dolor veritatis sequi id ipsum quis perferendis. Deserunt labore, aliquam illo veniam optio voluptatibus.',
  },
  {
    id: 2,
    image: img,
    name: 'lamen',
    totalItems: 1,
    category: 'vegetable',
    note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi itaque vero culpa, corporis nihil quibusdam expedita dolor veritatis sequi id ipsum quis perferendis. Deserunt labore, aliquam illo veniam optio voluptatibus.',
  },
  {
    id: 3,
    image: img,
    name: 'blueberry',
    totalItems: 1,
    category: 'fruit and vegetable',
    note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi itaque vero culpa, corporis nihil quibusdam expedita dolor veritatis sequi id ipsum quis perferendis. Deserunt labore, aliquam illo veniam optio voluptatibus.',
  },
  {
    id: 4,
    image: img,
    name: 'orange',
    totalItems: 1,
    category: 'fruit and vegetable',
    note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi itaque vero culpa, corporis nihil quibusdam expedita dolor veritatis sequi id ipsum quis perferendis. Deserunt labore, aliquam illo veniam optio voluptatibus.',
  },
  {
    id: 5,
    image: img,
    name: 'mango',
    totalItems: 1,
    category: 'fruit and vegetable',
    note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi itaque vero culpa, corporis nihil quibusdam expedita dolor veritatis sequi id ipsum quis perferendis. Deserunt labore, aliquam illo veniam optio voluptatibus.',
  },
  {
    id: 6,
    image: img,
    name: 'pine',
    totalItems: 1,
    category: 'fruit',
    note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi itaque vero culpa, corporis nihil quibusdam expedita dolor veritatis sequi id ipsum quis perferendis. Deserunt labore, aliquam illo veniam optio voluptatibus.',
  },
  {
    id: 7,
    image: img,
    name: 'apple',
    totalItems: 1,
    category: 'vegetable',
    note: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi itaque vero culpa, corporis nihil quibusdam expedita dolor veritatis sequi id ipsum quis perferendis. Deserunt labore, aliquam illo veniam optio voluptatibus.',
  },
]
export default List
